// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars_old = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Logiks Reports",
      items: [
        "logiks-reports/getting-started",
        "logiks-reports/basic-example",
        "logiks-reports/core-concepts",
        "logiks-reports/props",

        {
          type: "category",
          label: "Configuration",
          items: [
            "logiks-reports/configuration/rules",
            "logiks-reports/configuration/formatters",
            "logiks-reports/configuration/slot-bindings",
            "logiks-reports/configuration/actions-buttons",
            "logiks-reports/configuration/overview",
            "logiks-reports/configuration/top-level",
            "logiks-reports/configuration/source",
            "logiks-reports/configuration/datagrid",
            "logiks-reports/configuration/toolbar",
          ],
        },

        {
          type: "category",
          label: "Templates",
          items: [
            "logiks-reports/templates/grid",
            "logiks-reports/templates/cards",
            "logiks-reports/templates/kanban",
            "logiks-reports/templates/calendar",
            "logiks-reports/templates/gallery",
            "logiks-reports/templates/gantt",
            "logiks-reports/templates/gmap",
          ],
        },

        {
          type: "category",
          label: "Examples",
          items: [
            "logiks-reports/examples/basic-report",
            "logiks-reports/examples/api-report",
            "logiks-reports/examples/kanban-board",
            "logiks-reports/examples/dashboard-cards",
          ],
        },

        {
          type: "category",
          label: "Guides",
          items: [
            "logiks-reports/guides/common-use-cases",
            "logiks-reports/guides/best-practices",
            "logiks-reports/guides/common-mistakes",
          ],
        },
      ],
    },
  ],
};
export default sidebars_old;
